use_frameworks!

platform :ios, '9.0'

target 'MZKit_Example' do
  pod 'MZKit', :path => '../'

  target 'MZKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
